### ISSUE TITLE
Initial pull does not compile

### ISSUE THREAD

**Issue by alino95** [HPCE/hpce-2016-cw4#2]
Machine: Mac with macOS Sierra

Compiler Error: 

`src/layers/layer_factory.cpp:34:25: error: invalid operands to binary expression
      ('const std::string' (aka 'const basic_string<char, char_traits<char>,
      allocator<char> >') and 'const char *')
    }else if(layerEngine=="auto"){`

I googled the error and `#include <iostream>` in layer.hpp solves the issue.

**Comment by m8pple** [comment]
Thanks, for the problem and the solution.

I tried it on various windows and linuxes, but didn't have an OS X handy to try.
