### ISSUE TITLE
Bin file reading in run_network.cpp

### ISSUE THREAD

**Issue by DominicCYK** [HPCE/hpce-2016-cw4#3]
I suspect the line 
` std::string config=argv[1];`
should be 
` std::string config=argv[i];`
so as to read different layer binary files.

**Comment by m8pple** [comment]
Oh - yes, definitely. Thanks!

It looks like it was correct in the thing that generates graphs,
so I didn't notice.

(I took out the variable network size stuff, so I missed that when testing).

**Comment by m8pple** [comment]
Oh, and the variable engine thing would have caught that as well. It's a
shame, there was some fun stuff in there.
