### ISSUE TITLE
Typo in generate_sparse_layer.cpp

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw4#4]
```
<...>
if(argc>1){
    nIn=atoi(argv[1]);
}
if(argc>2){
    nOut=atoi(argv[2]);
}
if(sparsity>3){
    sparsity=strtod(argv[3],0);
}
<...>
```

`sparsity>3` should be `argc>3`

Also, ` fprintf(stderr, "Warning : suggest using generate_dense for sparsity > 0.25.\n");`, is there a generate_dense file?

**Comment by m8pple** [comment]
Yes, you're right - it's left-over from the more complicated original.
I'll fix those - thanks.
