### ISSUE TITLE
Final testing parameters

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw4#5]
For `Task: produce a plot exploring execution time (y) against input ratio (input-layer-size / output-layer-size) for a single layer, called results/single_layer_ratio_vs_time.pdf.`

Are there any standard parameters we should be using? There is an "infinite" number of input/output layer sizes available. Should we also be using default density?

**Comment by m8pple** [comment]
This is more exploratory, so seeing if you can find interesting parameters
that result in interesting scaling. I'm not looking for (or expecting) any
specific curve or output.

For example, you'll see that there is a lot of overhead for the file IO,
but are there parameters where that overhead starts to drop relative
to the compute? Possibly so, possibly not. It might depend on how
much data is being put through (e.g. startup cost versus cost per processed
input vector).

I'm more just laying out an application with some interesting performance properties
that people can play with - for most of the default ones it is somewhat less interesting.

Sparsity can definitely affect things, though possibly less than you might think,
unless other parameters are varied. For many parameterisations the app will
be IO-limited - for others it may well be memory limited (the other kind
of IO).

**Comment by jeremych1000** [comment]
Thanks - I'll do some more testing.
