### ISSUE TITLE
Script Writing - Best Practices?

### ISSUE THREAD

**Issue by nar213** [HPCE/hpce-2016-cw4#8]
When generating `results/single_layer_ratio_vs_time.pdf` the script I've written feels excessive and full of dodgy hacks such as altering run_network.cpp to remove the print to stderr. Could you recommend a more compact way of writing the script below that doesn't include removing stderr from run_network.cpp? 

Would you be able to release the timing scripts you used in CW1-CW3 as examples of how to write these kinds of scripts in a cleaner manner?

```
cat /dev/urandom | head -c 1048576 > w/random.bin
mkdir -p w

filename="results/single_layer_ratio.csv"
array=(512 1024 2048 4096 8192);
engines=("simple" "par_for_naive" "par_for_atomic" "clustered" "par_for_clustered")

printf "Engine, 2nd Layer (1st=2048), Time \n" > $filename
for i in "${array[@]}"
do
   bin/generate_sparse_layer 2048 $i > w/layer_${i}.bin
   for j in "${engines[@]}"
   do
      printf $j>>$filename;
      printf "," >> $filename;
      printf $i>>$filename;
      printf "," >> $filename;
      (gtime -f "%e" cat w/random.bin | bin/run_network w/layer_${i}.bin:${j}> /dev/null) 2>&1 |tr -d "\n" >> $filename;
      printf "\n">>$filename;
      echo "${i} ${j}"
   done
done
```

**Comment by jeremych1000** [comment]
1. Maybe have a check to see if file exists before generating to prevent excessive disk writing (32768 is like 800 MB big).
2. You can split your layer generation in another script and call that in your current script for modularity.
3. You can have your 4 printf's on one line, do `printf "asdf %u %u %u" "$a" $b" "$c"`
4. You can re-route stderr to dev by doing `2> /dev/null`. Same logic as you re-routing `gtime`'s stderr to stdout by doing `2>&1`.
5. Choose either echo or printf, and stick with it. I'd recommend printf for bash.

**Comment by nar213** [comment]
Thanks Jeremy, those changes weren't too difficult to make, for clarity I haven't shown step 2

```
randomFile="w/random.bin"
csvFile="results/single_layer_ratio.csv"
engines=("simple" "par_for_naive" "par_for_atomic" "clustered" "par_for_clustered")
sizes=(1024 2048 4096 8192 16384);
constantSize=4096;

if [ -f "$randomFile" ];
then
   printf "File "$randomFile" exists \n"
else
  printf "File "$randomFile" does not exist. Generating... \n"
  mkdir -p w
  cat /dev/urandom | head -c 2097152 > "$randomFile"
fi

printf "Engine, 2nd Layer (1st="$constantSize"), Time \n" > "$csvFile"

for i in "${sizes[@]}"
do
   bin/generate_sparse_layer "$constantSize" "$i" > w/layer_"$i".bin
   for j in "${engines[@]}"
   do
      printf "%s, %u, " "$j" "$i" >> "$csvFile";
      (gtime -f "%e\n" cat $randomFile | bin/run_network w/layer_"$i".bin:"$j" > /dev/null 2>/dev/null) 2>> "$csvFile";
      printf ""$i" "$j" \n"
   done
done
```

**Comment by m8pple** [comment]
I agree with pretty much everything Jeremy says, particularly the quoting of variables.

On a similar note, it is a good idea to use the ${} curly brackets everywhere.

Other things which can be useful are to add automatic error handling traps:

- `set -o errexit` - If any command fails, fail the script

- `set -o pipefail` - If part of a pipeline fails, then the whole thing fails.

Some people took a best-practises list and tried to turn it into a library, see:
- http://kvz.io/blog/2013/11/21/bash-best-practices/
- http://bash3boilerplate.sh/

I can put my scripts up, but unfortunately they don't really represent
best-practises. They're designed to run in a semi-manual way, so I have
to keep an eye on them for failures. I'll try and extract them and put
them somewhere, but it might take me a while.
